export interface TarotCard {
  id: number;
  name: string;
  suit: "major" | "wands" | "pentacles" | "swords" | "cups";
  romanNumeral: string;
  symbol: string;
  // Upright meanings
  upright: string;
  love: string;
  career: string;
  money: string;
  home: string;
  spiritual: string;
  // Reversed meaning
  reversed: string;
}

export const TAROT_DECK: TarotCard[] = [
  // ─── MAJOR ARCANA ──────────────────────────────────────────────────────────
  {
    id: 0, name: "The Fool", suit: "major", romanNumeral: "0", symbol: "🌱",
    upright: "New beginning, adventure, fresh energy, and taking a leap of faith",
    love: "A new emotional path opens, possibly after a breakup or period of being closed off",
    career: "A new opportunity appears; act while the door is open",
    money: "An unexpected chance arrives; act with awareness rather than impulse",
    home: "Visitors, social energy, or a young person leaving home; a new chapter begins",
    spiritual: "A new soul path or discovery is beginning — trust the unknown",
    reversed: "Naivety, false promises, unrealistic thinking, or jumping in without enough awareness",
  },
  {
    id: 1, name: "The Magician", suit: "major", romanNumeral: "I", symbol: "🪄",
    upright: "Action, skill, communication, creativity, and the power to make things happen",
    love: "Strong communication and forgiveness open the door to new romantic potential",
    career: "New career direction, leadership, creative income, and real momentum",
    money: "Opportunity is here; use your skills and tools to generate the outcome you want",
    home: "The home becomes a place of gathering, ideas, and shared plans",
    spiritual: "Your confidence in your own power is growing — trust that you have what you need",
    reversed: "Manipulation, stalled projects, creative block, or delayed plans",
  },
  {
    id: 2, name: "The High Priestess", suit: "major", romanNumeral: "II", symbol: "🌙",
    upright: "Intuition, hidden knowledge, inner wisdom, and unconventional truth",
    love: "Hidden feelings or unspoken issues; trust your intuition about this person",
    career: "Success comes from noticing what is missing; seek advice from a trusted source",
    money: "The answer is not in the numbers alone — listen to what your instincts tell you",
    home: "A time for privacy, quiet reflection, and trusting what you sense beneath the surface",
    spiritual: "Deeper commitment, mentorship, and psychic awareness are calling you inward",
    reversed: "A trusted person may disappoint; hidden information may surface at an uncomfortable time",
  },
  {
    id: 3, name: "The Empress", suit: "major", romanNumeral: "III", symbol: "🌺",
    upright: "Abundance, nurture, creativity, productivity, joy, and growth",
    love: "Nurturing love, partnership, and emotional richness; family energy is strong",
    career: "Rewards from past effort; growth and good resource management are on your side",
    money: "A fertile time financially — past work begins to pay off; manage resources wisely",
    home: "Harmony, comfort, and possible expansion or improvement of the home",
    spiritual: "Creativity is your bridge to intuition; let yourself create freely",
    reversed: "Household conflict, lack of time or money, or stress with a nurturing figure",
  },
  {
    id: 4, name: "The Emperor", suit: "major", romanNumeral: "IV", symbol: "👑",
    upright: "Order, structure, authority, protection, boundaries, discipline, and tradition",
    love: "A committed partner, father figure, or authority; honouring commitment matters now",
    career: "Leadership, promotion, and success are available through discipline and responsibility",
    money: "Stability and structure bring security; protect what you have built",
    home: "Restoring order, setting clear boundaries, and protecting the space you share",
    spiritual: "You are guided and protected; your discipline creates the foundation for growth",
    reversed: "Disorder, controlling behaviour, poor leadership, or a need to assert your own values",
  },
  {
    id: 5, name: "The Hierophant", suit: "major", romanNumeral: "V", symbol: "🏛️",
    upright: "Commitment, education, tradition, unity, and shared values",
    love: "Commitment, deeper intimacy, and unity; aligning values in a relationship",
    career: "Diplomacy and cooperation help career growth; learning within a structured system",
    money: "Generosity and shared resources can support abundance; formal agreements matter",
    home: "Progress through cooperation, shared space, and mutual respect",
    spiritual: "Learning within a community or tradition brings deeper understanding",
    reversed: "Perfectionism, self-criticism, group chaos, or blocked communication",
  },
  {
    id: 6, name: "The Lovers", suit: "major", romanNumeral: "VI", symbol: "💞",
    upright: "Choice, love, alignment, important relationships, and long-term decision-making",
    love: "Falling in love or a meaningful romantic decision; choose based on genuine alignment",
    career: "Consider options carefully; avoid quick fixes in favour of long-term fulfilment",
    money: "A significant financial choice is before you — take your time with it",
    home: "A decision about where or with whom to build your future life",
    spiritual: "Inner unity and self-compassion are part of your deepest growth right now",
    reversed: "Choosing the easier option under pressure, betrayal, or sacrificing personal needs",
  },
  {
    id: 7, name: "The Chariot", suit: "major", romanNumeral: "VII", symbol: "🏆",
    upright: "Confidence, movement, determination, progress, and taking charge",
    love: "Relationship growth or determination to move forward after a difficult period",
    career: "Success, forward motion, and financial reward come through sustained effort",
    money: "Progress is available; focus your energy and take decisive action",
    home: "Travel or visitors from a distance may shift your home priorities temporarily",
    spiritual: "Leadership and group learning, balanced with quiet inner reflection",
    reversed: "Delay, wrong direction, arrogance, or a need to recheck your plans",
  },
  {
    id: 8, name: "Strength", suit: "major", romanNumeral: "VIII", symbol: "🦁",
    upright: "Courage, patience, emotional control, inner power, and calm persistence",
    love: "Healing relationship issues with patience; love grows stronger through grace",
    career: "Handle conflict calmly; observe before reacting in tense professional situations",
    money: "Avoid impulsive overspending; strength here is restraint and steady focus",
    home: "Supporting others through a difficult period with compassion and consistency",
    spiritual: "Your beliefs may be tested — stand firm in what you know to be true",
    reversed: "Avoiding challenges, hiding from confrontation, or failing to draw on inner strength",
  },
  {
    id: 9, name: "The Hermit", suit: "major", romanNumeral: "IX", symbol: "🕯️",
    upright: "Reflection, solitude, healing, wisdom, and self-knowledge",
    love: "Healing after relationship endings; a period of turning toward yourself",
    career: "A slower pace, education over income, or taking space to reconsider your direction",
    money: "This is a time for careful planning rather than bold financial moves",
    home: "Thoughtful preparation for home projects rather than immediate action",
    spiritual: "Retreat, mentoring, contemplation, writing, and reading deepen your inner life",
    reversed: "Isolation, stubbornness, fear of reaching out, or needing connection but refusing it",
  },
  {
    id: 10, name: "Wheel of Fortune", suit: "major", romanNumeral: "X", symbol: "🎡",
    upright: "Change, destiny, improvement, cycles turning, and movement",
    love: "Destiny is influencing your relationships; right place, right time energy is present",
    career: "Swift improvement; go with the flow rather than overthinking the next step",
    money: "Events may shift quickly for the better; stay open and ready to receive",
    home: "Unexpected household changes or temporary disruptions that lead somewhere better",
    spiritual: "Dreams and hidden messages carry guidance; your unconscious knows the way",
    reversed: "The end of a negative cycle; you are almost through the most difficult phase",
  },
  {
    id: 11, name: "Justice", suit: "major", romanNumeral: "XI", symbol: "⚖️",
    upright: "Fairness, resolution, balance, truth, and important decisions",
    love: "Better balance with loved ones; clarity about a relationship situation is coming",
    career: "Interviews, meetings, and professional decisions may resolve in your favour",
    money: "Debts and financial matters have a chance to resolve positively and fairly",
    home: "Property issues, documents, and legal agreements become clearer",
    spiritual: "Balancing your spiritual interests with the practical demands of your life",
    reversed: "Injustice, an unfavourable decision, manipulation, or need for outside support",
  },
  {
    id: 12, name: "The Hanged Man", suit: "major", romanNumeral: "XII", symbol: "⏸️",
    upright: "Delay, surrender, new perspective, sacrifice, and meaningful pause",
    love: "A relationship pause or time apart; use this space to reassess what you truly want",
    career: "Delayed work or pending decisions; what feels like waiting may be incubation",
    money: "Stalled financial decisions; resist forcing an outcome before the timing is right",
    home: "Home projects or plans may be postponed; patience is called for now",
    spiritual: "You are processing something deep; this pause holds important inner insight",
    reversed: "Indecision, fantasy, procrastination, or a refusal to accept what is practically true",
  },
  {
    id: 13, name: "Death", suit: "major", romanNumeral: "XIII", symbol: "🦋",
    upright: "Transformation, endings, release, transition, and new beginnings",
    love: "A necessary ending or shift in a relationship pattern that no longer serves you",
    career: "A career change or role transition that creates space for long-term benefit",
    money: "Control spending and release attachments to outdated financial habits",
    home: "Leaving or transforming a living situation to fit the next chapter of life",
    spiritual: "Something old must be released so something new and aligned can emerge",
    reversed: "Holding on to the past, resisting necessary change, or refusing to move forward",
  },
  {
    id: 14, name: "Temperance", suit: "major", romanNumeral: "XIV", symbol: "⚗️",
    upright: "Balance, reconciliation, patience, healing, and managing many demands at once",
    love: "Meeting expectations and healing past issues; patience deepens connection",
    career: "Detail-oriented problem solving and managing volatile dynamics with calm",
    money: "Balance your outgoings carefully; ignored debts or responsibilities need attention",
    home: "Family demands across generations require skillful, compassionate integration",
    spiritual: "Staying grounded, setting clear boundaries, and finding the still centre within",
    reversed: "Difficult memories dominating the present, ignored responsibilities, or poor balance",
  },
  {
    id: 15, name: "The Devil", suit: "major", romanNumeral: "XV", symbol: "⛓️",
    upright: "Control, attachment, addiction, fear, guilt, obligation, and unhealthy bonds",
    love: "Toxic attachment, obligation replacing love, or a pattern that feels impossible to leave",
    career: "Feeling trapped in unsatisfying work or under a manipulative authority",
    money: "Trapped by loans, agreements, or financial patterns that feel out of your control",
    home: "Feeling unsafe or burdened by debt, obligation, or unhealthy household dynamics",
    spiritual: "Be aware of energy-draining people or belief systems that diminish your power",
    reversed: "Repeating cycles of entrapment, temptation, or returning to what was already left",
  },
  {
    id: 16, name: "The Tower", suit: "major", romanNumeral: "XVI", symbol: "💥",
    upright: "Sudden endings, disruption, revelation, collapse, and breakthrough",
    love: "A revelation or instability that tests the foundation of a relationship",
    career: "Sudden management or structural changes; financial risks that force a reckoning",
    money: "An unexpected financial shock; the structure that felt secure may need rebuilding",
    home: "A forced or dramatic change of living situation reveals something important",
    spiritual: "A powerful wake-up call that dismantles what no longer truly serves your growth",
    reversed: "Overthinking the past, blame, rumination, or difficulty releasing what has happened",
  },
  {
    id: 17, name: "The Star", suit: "major", romanNumeral: "XVII", symbol: "⭐",
    upright: "Hope, inspiration, guidance, healing, talent, and faith",
    love: "Harmony, soulmate guidance, and emotional peace are drawing closer",
    career: "Recognition, fitting work, and rewards are on their way; your gifts are seen",
    money: "Money and resources are beginning to flow in the right direction",
    home: "Nesting, decluttering, and feeling truly at home within yourself and your space",
    spiritual: "You are protected and guided; creative pursuits bring healing and light",
    reversed: "Unrealistic ideas or expectations that need a grounding reality check",
  },
  {
    id: 18, name: "The Moon", suit: "major", romanNumeral: "XVIII", symbol: "🌕",
    upright: "Uncertainty, emotion, intuition, hidden fears, and unclear choices",
    love: "Something feels unclear or off; emotions run high and the full picture is not yet visible",
    career: "Questioning your ambition or direction; demanding projects cloud your judgment",
    money: "Avoid rushed financial decisions; you may not see the full picture yet",
    home: "Doubts around moving or renovating; quiet space and time are needed",
    spiritual: "Heightened sensitivity and refined intuition; trust what you feel beneath the surface",
    reversed: "Avoiding emotional issues, disillusionment, or feeling unsafe; a risk of inaction",
  },
  {
    id: 19, name: "The Sun", suit: "major", romanNumeral: "XIX", symbol: "☀️",
    upright: "Joy, success, vitality, protection, health, and happiness",
    love: "Love as safety and joy; warmth and genuine connection are available to you",
    career: "Recognition, status, and successful proposals; your work is being seen and valued",
    money: "A bright financial period; successful outcomes and well-earned rewards arrive",
    home: "Warmth, friendship, children, and comfort settle into your home life",
    spiritual: "Sharing your light with others and returning to joy after a period of difficulty",
    reversed: "Delays, frustration, or temporary setbacks; plans are on hold but recovery is near",
  },
  {
    id: 20, name: "Judgment", suit: "major", romanNumeral: "XX", symbol: "📯",
    upright: "Review, second chances, reflection, awakening, and reconsideration",
    love: "A past relationship may return or deserve reconsideration; old patterns resurface",
    career: "Disputes clear, opportunities return, and the situation begins to move again",
    money: "Cash flow improves; what was owed or delayed starts to come back",
    home: "Second thoughts about property; attraction to familiar or meaningful places",
    spiritual: "A wake-up call strengthens your connection to inner guidance and higher purpose",
    reversed: "Guilt, worry, being stuck in the past, or excessive self-examination that stalls progress",
  },
  {
    id: 21, name: "The World", suit: "major", romanNumeral: "XXI", symbol: "🌍",
    upright: "Completion, success, reward, wholeness, celebration, and a new phase",
    love: "A fulfilling relationship, celebration, or the arrival of something long hoped for",
    career: "Awards, travel, exam or interview success, and recognition for your efforts",
    money: "Money arrives from past effort, generosity, or a completed project",
    home: "Success in home projects; possible interest in a new or meaningful home",
    spiritual: "Integration of the self, wholeness, and the joy of inner completion",
    reversed: "Delayed opportunity, feeling limited or close but not quite there; patience is needed",
  },

  // ─── WANDS ────────────────────────────────────────────────────────────────
  {
    id: 22, name: "Ace of Wands", suit: "wands", romanNumeral: "Ace", symbol: "🔥",
    upright: "New beginnings, inspiration, new work, creativity, and fresh romantic or travel energy",
    love: "Exciting new romantic energy or the rekindling of passion in an existing connection",
    career: "A new work opportunity or creative project is ready to be launched",
    money: "A new income stream or enterprise opportunity is opening up",
    home: "Fresh energy in the home; a creative project or social gathering begins",
    spiritual: "A spark of inspiration is guiding you toward your next creative or soul path",
    reversed: "Poor timing, lack of support, delayed ideas or travel, or stalled beginnings",
  },
  {
    id: 23, name: "Two of Wands", suit: "wands", romanNumeral: "2", symbol: "🗺️",
    upright: "Planning, looking ahead, partnerships, collaboration, and future vision",
    love: "Planning a future together; early romantic collaboration and shared direction",
    career: "A partnership or collaboration is worth exploring; map out the next step forward",
    money: "Planning and looking ahead creates financial opportunity; act on your vision",
    home: "Discussing future plans for home or lifestyle with someone who shares your vision",
    spiritual: "Your vision of what is possible is expanding; trust the seeds you are planting",
    reversed: "Different needs, conflicting directions, or a project drifting off course",
  },
  {
    id: 24, name: "Three of Wands", suit: "wands", romanNumeral: "3", symbol: "🌅",
    upright: "New experiences, travel, creative projects, education, expansion, and inspiration",
    love: "An expanding sense of possibility in love; someone may come from afar",
    career: "Creative projects gain momentum; education or travel supports professional growth",
    money: "Expansion is possible; explore new income avenues with confidence",
    home: "A move, renovation, or exciting new chapter is beginning to take shape",
    spiritual: "New ideas and experiences are broadening your spiritual understanding",
    reversed: "Communication problems, misunderstandings, delays, or blocked plans",
  },
  {
    id: 25, name: "Four of Wands", suit: "wands", romanNumeral: "4", symbol: "🎊",
    upright: "Relaxation, freedom, celebration, change of scene, and a welcome pause",
    love: "Celebration, harmony, and enjoying the happiness that has been built together",
    career: "A milestone deserves to be celebrated; take time to acknowledge how far you have come",
    money: "Financial stability allows for a well-earned rest or treat",
    home: "A happy event at home or a joyful change of scene refreshes your energy",
    spiritual: "Rest, gratitude, and celebration are as sacred as effort and striving",
    reversed: "Escapism, temporary setbacks, or delayed travel and celebrations",
  },
  {
    id: 26, name: "Five of Wands", suit: "wands", romanNumeral: "5", symbol: "🤺",
    upright: "Competition, lively debate, testing of boundaries, and challenge without deep conflict",
    love: "Friction or mismatched energy; healthy debate can clear the air if approached with care",
    career: "Competition and differing opinions at work; stand your ground without escalating",
    money: "Competing priorities or offers; weigh your options carefully before committing",
    home: "Lively disagreements at home; listen as well as speak",
    spiritual: "Being challenged strengthens your convictions when you hold them with humility",
    reversed: "Ego, talking without listening, or difficulty finding common ground",
  },
  {
    id: 27, name: "Six of Wands", suit: "wands", romanNumeral: "6", symbol: "🎖️",
    upright: "Victory, deserved success, recognition, and applause for your efforts",
    love: "Recognition and appreciation within a relationship; you are seen and valued",
    career: "Well-earned professional success and public recognition are arriving",
    money: "Financial rewards are coming in acknowledgment of your hard work",
    home: "A proud and joyful period at home; achievements are celebrated together",
    spiritual: "Your inner work is paying off; trust the path you have chosen",
    reversed: "Success feels out of reach for now; a different approach is needed",
  },
  {
    id: 28, name: "Seven of Wands", suit: "wands", romanNumeral: "7", symbol: "🛡️",
    upright: "Standing your ground, defending your beliefs, protecting others, and persistence",
    love: "Protecting what you value in a relationship; do not give up without cause",
    career: "You are holding a strong position; stay firm against pressure or competition",
    money: "Defend your financial interests and do not allow others to take advantage",
    home: "Standing up for your values within the home or family context",
    spiritual: "Your convictions are being tested; persistence and integrity are your allies",
    reversed: "Doubting your motivation, wounded pride, or needing to know when to step back",
  },
  {
    id: 29, name: "Eight of Wands", suit: "wands", romanNumeral: "8", symbol: "💨",
    upright: "Fast action, news, movement, travel, communication, and projects moving quickly",
    love: "Things are moving quickly in love; a message or invitation may be coming",
    career: "Rapid professional progress; communication and deadlines require your full attention",
    money: "Financial movement is swift; be ready to act on opportunities quickly",
    home: "News or changes affecting the home arrive faster than expected",
    spiritual: "Energy is flowing and accelerating; align with the momentum rather than resisting it",
    reversed: "Misunderstandings, unclear intentions, or a need to double-check paperwork",
  },
  {
    id: 30, name: "Nine of Wands", suit: "wands", romanNumeral: "9", symbol: "💪",
    upright: "Endurance, strong position, resource management, resilience, and fatigue",
    love: "A relationship that has weathered difficulty; rest is needed before the next step",
    career: "You are close to the end of a gruelling stretch; stay resilient just a little longer",
    money: "Manage your resources carefully; you have enough but must protect it",
    home: "Holding strong at home despite weariness; others are counting on your steadiness",
    spiritual: "Your endurance is itself a spiritual practice; honour how far you have come",
    reversed: "Burnout, an unsustainable schedule, or a desperate need to rest and back off",
  },
  {
    id: 31, name: "Ten of Wands", suit: "wands", romanNumeral: "10", symbol: "📦",
    upright: "Too many responsibilities, a heavy burden, and the need to prioritise",
    love: "Pressure and overwhelm may be affecting your relationships; something must be put down",
    career: "You are carrying more than your share; it is time to delegate or let something go",
    money: "Financial strain from taking on too much; reassess what is truly necessary",
    home: "Domestic responsibilities feel crushing; ask for help and share the load",
    spiritual: "Release what is not yours to carry; your path requires you to travel lighter",
    reversed: "Unreasonable demands from others, confusion, or self-created pressure",
  },
  {
    id: 32, name: "Page of Wands", suit: "wands", romanNumeral: "Page", symbol: "📬",
    upright: "Invitations, opportunities, creativity, social energy, and a chatty new project",
    love: "Playful, flirtatious energy; an invitation or social opportunity opens a new door",
    career: "A creative opportunity or invitation to collaborate is coming your way",
    money: "Small but promising financial news; an idea worth exploring is arriving",
    home: "Fresh, social, and creative energy livens up home life",
    spiritual: "A new creative spark connects you to your deeper self and authentic expression",
    reversed: "Disappointing news, negative opinions, or someone who does not truly listen",
  },
  {
    id: 33, name: "Knight of Wands", suit: "wands", romanNumeral: "Knight", symbol: "🚀",
    upright: "Energy, speed, ideas, movement, an exciting if unpredictable new direction",
    love: "Exciting but unpredictable romantic energy; passion is strong but consistency matters",
    career: "Fast-moving professional energy; great ideas need follow-through to succeed",
    money: "Quick financial action is possible; ensure stability before leaping",
    home: "A possible house move or burst of renovating energy arrives suddenly",
    spiritual: "Passionate energy is driving you; channel it with intention",
    reversed: "Drama, unstable energy, or a big idea with no follow-through",
  },
  {
    id: 34, name: "Queen of Wands", suit: "wands", romanNumeral: "Queen", symbol: "🌻",
    upright: "Personal power, inspiration, leadership, creativity, and confident progress",
    love: "A warm, magnetic partner energy; emotional honesty and self-assurance attract connection",
    career: "You are in a position of real creative leadership; own your expertise",
    money: "Confidence and resourcefulness open financial doors",
    home: "The home is a place of warmth, colour, and creative life under your influence",
    spiritual: "Your creative fire is a direct channel to your highest self",
    reversed: "Lack of understanding, envy, insensitivity, or dimming your own light for others",
  },
  {
    id: 35, name: "King of Wands", suit: "wands", romanNumeral: "King", symbol: "🦊",
    upright: "Happiness, charisma, emotional openness, and stronger bonds with loved ones",
    love: "A warm and open-hearted energy brings deeper connection and renewed bonds",
    career: "Charismatic leadership and decisive action lead to professional recognition",
    money: "Financial generosity and vision create abundance that is shared",
    home: "Warmth, togetherness, and a joyful, expressive home environment",
    spiritual: "Your passion and purpose are aligned; lead from the heart",
    reversed: "Lack of trust, self-obsession, or an unwillingness to compromise",
  },

  // ─── PENTACLES ──────────────────────────────────────────────────────────────
  {
    id: 36, name: "Ace of Pentacles", suit: "pentacles", romanNumeral: "Ace", symbol: "💰",
    upright: "Money, success, financial news, a new job, enterprise, and opportunity",
    love: "A grounded, stable new connection or a relationship becoming more committed",
    career: "A new job or financial opportunity is opening; this is a seed worth planting",
    money: "Positive financial news or a new income opportunity is arriving",
    home: "Practical improvements to home life are possible; a stable foundation is forming",
    spiritual: "Grounding your spiritual values in everyday, practical action",
    reversed: "A money or earning opportunity is delayed, missed, or stalled",
  },
  {
    id: 37, name: "Two of Pentacles", suit: "pentacles", romanNumeral: "2", symbol: "🤹",
    upright: "Decision, financial balancing, resourcefulness, and managing competing demands",
    love: "Juggling relationship needs and personal priorities; find a sustainable rhythm",
    career: "Balancing multiple work responsibilities or a career decision that needs careful thought",
    money: "Managing money across competing needs; a financial arrangement requires attention",
    home: "A possible home move or the challenge of balancing home and work demands",
    spiritual: "Finding balance in your spiritual practice amid the demands of daily life",
    reversed: "Lack of support, limited money, or a decision made against your true interests",
  },
  {
    id: 38, name: "Three of Pentacles", suit: "pentacles", romanNumeral: "3", symbol: "🔨",
    upright: "Collaboration, skilled craftsmanship, recognised talent, and building something real",
    love: "Working together to build something lasting; mutual effort strengthens the bond",
    career: "Your skills are being recognised; collaboration and mentorship open new doors",
    money: "Earnings from skilled work; financial progress through quality and attention to detail",
    home: "Renovation, improvement, or a new home project is underway or approaching",
    spiritual: "Dedicated practice brings real, tangible spiritual growth",
    reversed: "Lack of recognition, delays, or financial difficulty in work or property matters",
  },
  {
    id: 39, name: "Four of Pentacles", suit: "pentacles", romanNumeral: "4", symbol: "🏦",
    upright: "Security, strong foundations, good health, and enjoying what has been built",
    love: "Stability and security in a relationship; be careful not to let caution become rigidity",
    career: "A solid professional position; protect what you have built with care",
    money: "Financial security is present but watch for excessive hoarding or fear of loss",
    home: "A well-established, secure home; enjoying comfort and stability",
    spiritual: "Grounding and security are healthy, but release where you cling too tightly",
    reversed: "False security, wrong assumptions, or a period of temporary instability",
  },
  {
    id: 40, name: "Five of Pentacles", suit: "pentacles", romanNumeral: "5", symbol: "😰",
    upright: "Fear of poverty, insecurity, rejection, and a call to avoid impulsive decisions",
    love: "Financial or material stress is affecting emotional intimacy and closeness",
    career: "Insecurity about job stability or income; avoid rash decisions while afraid",
    money: "Financial anxiety is present; face the reality of the situation and seek practical support",
    home: "Worry or hardship affecting domestic life; help is available if you ask",
    spiritual: "Even in difficulty, remember you are not alone; faith and community sustain you",
    reversed: "Money or work problems affecting relationships; face the urgent issues honestly",
  },
  {
    id: 41, name: "Six of Pentacles", suit: "pentacles", romanNumeral: "6", symbol: "🤲",
    upright: "Gifts, generosity, kindness, receiving help, and a positive and giving outlook",
    love: "Generosity and giving freely within a relationship creates warmth and trust",
    career: "A bonus, raise, or act of professional kindness comes your way",
    money: "Money flows in through generosity, gifts, or well-deserved financial support",
    home: "Acts of care and kindness in the home create a sense of safety and abundance",
    spiritual: "Giving and receiving with an open heart is a profound spiritual act",
    reversed: "Money secrets, unpaid debts, or obligations avoided; money owed may not return",
  },
  {
    id: 42, name: "Seven of Pentacles", suit: "pentacles", romanNumeral: "7", symbol: "🌾",
    upright: "Potential, progress, patience, appreciating effort, and staying the course",
    love: "A relationship in the middle of its growth; patience will reveal if it is worth investing in",
    career: "Your efforts are compounding; stay focused and do not abandon the work prematurely",
    money: "A financial investment is maturing; patience and steady attention will pay off",
    home: "Home improvements or plans need time to unfold; trust the process",
    spiritual: "The seeds of your spiritual practice are growing quietly beneath the surface",
    reversed: "Frustration with the pace of progress; a need for fresh perspective or strategy",
  },
  {
    id: 43, name: "Eight of Pentacles", suit: "pentacles", romanNumeral: "8", symbol: "⚒️",
    upright: "Hard work, developing skills, valuable experience, and detail paying off",
    love: "Investing consistent effort in a relationship builds something genuinely lasting",
    career: "Mastery through focused practice; qualifications and detail-oriented work are rewarded",
    money: "Diligent, skilled work creates steady income; do not cut corners",
    home: "Careful, patient attention to home improvements brings lasting results",
    spiritual: "Dedicated, daily spiritual practice is the source of real inner development",
    reversed: "Work feels unrewarding; redirect your effort to where it is genuinely appreciated",
  },
  {
    id: 44, name: "Nine of Pentacles", suit: "pentacles", romanNumeral: "9", symbol: "💎",
    upright: "Financial security, luxury, lifestyle appreciation, self-sufficiency, and well-earned comfort",
    love: "Self-sufficiency and inner contentment create the most attractive and healthy foundation for love",
    career: "Financial independence and professional confidence you have earned through real effort",
    money: "You are entering or already in a period of genuine financial security and comfort",
    home: "Enjoying the comfort and beauty of your home; a time to appreciate what has been built",
    spiritual: "Gratitude for what has been cultivated; you are the garden and the gardener",
    reversed: "Domestic imbalance, difficulty organising money, work, and home life together",
  },
  {
    id: 45, name: "Ten of Pentacles", suit: "pentacles", romanNumeral: "10", symbol: "🏡",
    upright: "Material comfort, stable relationships, family prosperity, and long-term security",
    love: "A deeply stable and committed relationship; long-term partnership and shared security",
    career: "Long-term professional success and financial rewards from sustained dedication",
    money: "Material wealth, inheritance, or the security of solid long-term financial planning",
    home: "A prosperous, happy, and multigenerational family home; a legacy of love",
    spiritual: "The deep fulfilment of a life built with integrity and shared with those you love",
    reversed: "Debt, family disagreement, or a lack of contribution to shared resources",
  },
  {
    id: 46, name: "Page of Pentacles", suit: "pentacles", romanNumeral: "Page", symbol: "📜",
    upright: "Good financial news, a small cash opportunity, a job offer, or a loyal helpful person",
    love: "A grounded, sincere offer of affection or a dependable new romantic connection",
    career: "A job opportunity or positive professional news is on its way",
    money: "Good financial news or a small but real cash opportunity is arriving",
    home: "A helpful and reliable person brings useful support to your home or family life",
    spiritual: "A new opportunity to ground your spiritual values in practical action",
    reversed: "An empty offer, disorganisation, a need for money, or unreliable support",
  },
  {
    id: 47, name: "Knight of Pentacles", suit: "pentacles", romanNumeral: "Knight", symbol: "🐢",
    upright: "Consistent effort, steady rewards, reliable relationships, and trustworthy people",
    love: "A steady, reliable, and genuinely trustworthy romantic energy; slow but lasting",
    career: "Consistent, reliable professional effort leads to steady and real rewards",
    money: "Slow and steady financial progress; trust the method and stay consistent",
    home: "A dependable person helps maintain or improve your home situation",
    spiritual: "Disciplined and consistent practice builds the most enduring spiritual foundation",
    reversed: "Money or benefits owed, a feeling of being cheated or misled, or quiet selfishness",
  },
  {
    id: 48, name: "Queen of Pentacles", suit: "pentacles", romanNumeral: "Queen", symbol: "🌿",
    upright: "Success, security, generosity, practical organisation, and connection to nature",
    love: "A nurturing, warm, and practically loving partner energy; safety and care are present",
    career: "Practical success and professional generosity; you manage resources well",
    money: "Financial stability and wise management create a sense of genuine security",
    home: "A comfortable, well-organised home with warmth, good food, and a nurturing atmosphere",
    spiritual: "Caring for your body and home environment is a form of spiritual devotion",
    reversed: "Financial instability, unexpected expenses, poor work-life balance, or unreliability",
  },
  {
    id: 49, name: "King of Pentacles", suit: "pentacles", romanNumeral: "King", symbol: "💼",
    upright: "Honesty, stability, cash flow, practical support, and problems being solved",
    love: "A stable, generous, and deeply reliable partner; someone who shows love through action",
    career: "A position of genuine authority and financial competence; problems are being solved",
    money: "Strong cash flow and practical financial wisdom bring stability and security",
    home: "A secure, well-provided-for home where disputes are resolved and support is reliable",
    spiritual: "Integrity, reliability, and the dignified expression of your values in daily life",
    reversed: "Secrecy, financial mismanagement, domestic disputes, or dishonesty",
  },

  // ─── SWORDS ─────────────────────────────────────────────────────────────────
  {
    id: 50, name: "Ace of Swords", suit: "swords", romanNumeral: "Ace", symbol: "⚔️",
    upright: "Victory, a favourable decision, intelligence, strategy, and a clear path forward",
    love: "Clarity cuts through confusion in a relationship; a direct honest conversation is needed",
    career: "A clear strategic decision leads to professional victory",
    money: "An intelligent financial strategy brings a favourable outcome",
    home: "A clear decision about home or family brings much-needed resolution",
    spiritual: "Mental clarity and truth create the conditions for genuine spiritual growth",
    reversed: "A decision goes against you, misjudgement, or unclear and clouded thinking",
  },
  {
    id: 51, name: "Two of Swords", suit: "swords", romanNumeral: "2", symbol: "🙈",
    upright: "Indecision, blocked progress, and the need to make a difficult but necessary choice",
    love: "You are avoiding a difficult truth in a relationship; the choice you delay still awaits",
    career: "A career decision is being postponed; the stalemate will not resolve itself",
    money: "Financial indecision is costing you; gather information and choose",
    home: "A domestic or family decision is being avoided; clarity requires courage",
    spiritual: "The mind creates the illusion of impossibility; the way forward exists",
    reversed: "The situation may not be as impossible as it feels; your powerlessness is partly illusion",
  },
  {
    id: 52, name: "Three of Swords", suit: "swords", romanNumeral: "3", symbol: "💔",
    upright: "Loss, grief, betrayal, painful truth, and necessary sorrow",
    love: "A painful truth or betrayal is surfacing; the grief, though real, leads to healing",
    career: "A professional disappointment or difficult news needs to be faced honestly",
    money: "Financial loss or a painful realisation about money requires honest acknowledgment",
    home: "A family conflict or hurtful event needs space to be grieved and processed",
    spiritual: "Grief and loss are sacred; allowing yourself to feel pain opens the door to healing",
    reversed: "Nearing the end of a painful period; anxiety is easing and recovery is close",
  },
  {
    id: 53, name: "Four of Swords", suit: "swords", romanNumeral: "4", symbol: "😴",
    upright: "Time out, rest, pause, recuperation, and healing from stress",
    love: "Space and rest are needed in a relationship; quiet time apart can bring perspective",
    career: "A necessary professional pause; exhaustion requires genuine recovery time",
    money: "Pause before making any major financial moves; rest and reflection serve you here",
    home: "A quiet, restful period at home is exactly what is needed right now",
    spiritual: "Withdrawal, stillness, and contemplation replenish your spirit",
    reversed: "Unwanted delays, enforced distance, or isolation from the people around you",
  },
  {
    id: 54, name: "Five of Swords", suit: "swords", romanNumeral: "5", symbol: "😤",
    upright: "Conflict, stress, humiliation, and emotional exhaustion from ongoing tension",
    love: "A power struggle or ongoing argument that is draining both people; choose your battles",
    career: "Workplace conflict, bullying, or a competitive dynamic that diminishes everyone",
    money: "Financial conflict or a dispute that is costing more than money",
    home: "Family tension or a conflict at home that is leaving everyone exhausted",
    spiritual: "Walk away from what is defeating you; not every battle is yours to fight",
    reversed: "Stop defending yourself to those who will never understand; choose peace instead",
  },
  {
    id: 55, name: "Six of Swords", suit: "swords", romanNumeral: "6", symbol: "⛵",
    upright: "Moving away from difficulty, peace returning, and a mental or emotional transition",
    love: "Leaving behind conflict or emotional turbulence; calmer waters are ahead",
    career: "A professional transition away from what was draining you; relief is coming",
    money: "Financial troubles are being left behind as you move toward a more stable situation",
    home: "A move or significant change of domestic scene brings much-needed peace",
    spiritual: "You are crossing into a calmer, clearer inner landscape; trust the transition",
    reversed: "You are ready to move on but circumstances are lagging; the timing is not yet right",
  },
  {
    id: 56, name: "Seven of Swords", suit: "swords", romanNumeral: "7", symbol: "🐍",
    upright: "Caution, trust issues, strategy, and protecting your information and resources",
    love: "Something may not be entirely honest in a relationship; trust your instincts",
    career: "Guard your professional ideas and information; not everyone has your best interests",
    money: "Protect your financial interests; be careful with contracts and agreements",
    home: "Guard the security of your home; not everyone in your circle is trustworthy",
    spiritual: "Be discerning about who you allow into your energy and your inner world",
    reversed: "Pressure and opposition; you are being pulled into someone else's game",
  },
  {
    id: 57, name: "Eight of Swords", suit: "swords", romanNumeral: "8", symbol: "🪢",
    upright: "Restriction, mental blocks, feeling trapped, and limited vision",
    love: "You feel more trapped in a relationship than you actually are; freedom is possible",
    career: "Mental blocks and overthinking are creating professional restriction; see clearly",
    money: "Financial anxiety creates the sensation of being trapped; you have more options than you think",
    home: "A sense of restriction at home that may be more mental than physical",
    spiritual: "The prison is largely of the mind; clarity and courage are the keys",
    reversed: "Adversity requires gathering your strength; freedom is within reach if you reach for it",
  },
  {
    id: 58, name: "Nine of Swords", suit: "swords", romanNumeral: "9", symbol: "😱",
    upright: "Insomnia, anxiety, worry, and a difficult period of stressful thoughts",
    love: "Anxiety about a relationship is taking a toll; worry is amplifying what is uncertain",
    career: "Professional anxiety and stress are affecting your sleep and wellbeing",
    money: "Financial worry creates sleepless nights; seek practical advice rather than spiralling",
    home: "A household concern is weighing heavily; sharing the burden will help",
    spiritual: "The night of the mind is darkest before clarity returns; ask for support",
    reversed: "Recurring negative thought patterns; the cycle can be broken with the right help",
  },
  {
    id: 59, name: "Ten of Swords", suit: "swords", romanNumeral: "10", symbol: "🌑",
    upright: "Sudden ending, painful clarity, a situation is over, and the path to move forward",
    love: "A relationship or dynamic has truly ended; painful as it is, it opens the way forward",
    career: "A professional ending or significant setback that, once accepted, frees you",
    money: "A financial loss or ending that, though difficult, draws a necessary line",
    home: "A domestic situation has run its course; the ending, though sharp, is final",
    spiritual: "The darkest point carries within it the seed of a genuine new beginning",
    reversed: "False hope or an unrealistic second chance; look at the evidence with clear eyes",
  },
  {
    id: 60, name: "Page of Swords", suit: "swords", romanNumeral: "Page", symbol: "📰",
    upright: "Small challenges, news, legal documents, a witty but sharp person",
    love: "Clever communication or a sharp-tongued person complicates a romantic situation",
    career: "Legal or contractual matters require careful attention; read all documents closely",
    money: "Financial news or paperwork that needs scrutiny before signing",
    home: "A young or witty person in the home may stir things up",
    spiritual: "Mental sharpness and curiosity are gifts; balance them with emotional openness",
    reversed: "Trouble with words, contracts, or documents; a troublemaker needs handling carefully",
  },
  {
    id: 61, name: "Knight of Swords", suit: "swords", romanNumeral: "Knight", symbol: "🗡️",
    upright: "Clear conflict, direct challenge, no hidden agenda, and political or professional honesty",
    love: "A direct and possibly confrontational energy in love; honesty may sting but clears the air",
    career: "A direct professional challenge or ally who says exactly what they mean",
    money: "A clear and possibly confrontational financial situation that demands directness",
    home: "Conflict at home that needs to be addressed head-on rather than avoided",
    spiritual: "Clarity and directness serve your growth; do not mistake bluntness for brutality",
    reversed: "Drama, ego, or a self-protective person who creates chaos rather than clarity",
  },
  {
    id: 62, name: "Queen of Swords", suit: "swords", romanNumeral: "Queen", symbol: "🧊",
    upright: "Independence, a sharp mind, warrior energy, self-reliance, and clear boundaries",
    love: "Self-reliance and clarity are your greatest romantic strengths right now",
    career: "Your sharp mind, independence, and direct communication are professional assets",
    money: "Independent financial thinking and clear-eyed decisions serve your interests well",
    home: "Setting clear, firm boundaries at home is an act of self-respect and care",
    spiritual: "Your intelligence is a spiritual gift; let it guide without letting it harden",
    reversed: "A formidable opponent, unreasonable demands, bitterness, or cutting anger",
  },
  {
    id: 63, name: "King of Swords", suit: "swords", romanNumeral: "King", symbol: "🔬",
    upright: "Problems solved, order restored, favourable decisions, and ambitious clarity",
    love: "Clear, honest, and fair communication resolves what has been tangled in a relationship",
    career: "An authority figure or your own clear judgment restores professional order",
    money: "A favourable financial decision or legal resolution comes through clear thinking",
    home: "Restored order and fair decision-making bring peace to the home",
    spiritual: "Intellectual clarity and integrity are the cornerstones of your current growth",
    reversed: "Power games, confusion, mistrust, or a destructive and domineering authority",
  },

  // ─── CUPS ────────────────────────────────────────────────────────────────────
  {
    id: 64, name: "Ace of Cups", suit: "cups", romanNumeral: "Ace", symbol: "💖",
    upright: "Falling in love, new passion, emotional beginning, happiness, creativity, and connection",
    love: "A powerful new emotional beginning; the heart is opening to genuine love and connection",
    career: "Creative passion and emotional inspiration fuel a new and meaningful project",
    money: "An emotional alignment with your work opens the door to new and fulfilling income",
    home: "A new emotional chapter fills the home with warmth, joy, and possibility",
    spiritual: "Your heart is opening; love in all its forms is your most direct path to the divine",
    reversed: "Temporary unhappiness, emotional delay, creative block, or an emotional beginning stalled",
  },
  {
    id: 65, name: "Two of Cups", suit: "cups", romanNumeral: "2", symbol: "🫂",
    upright: "Equal emotional connection, a soulmate, a true friend, and the meeting of two hearts",
    love: "A soulmate connection or the deepening of a genuine and balanced emotional bond",
    career: "A meaningful professional partnership built on mutual respect and shared vision",
    money: "A financial arrangement that benefits both parties equally and fairly",
    home: "A deeply loving, balanced, and harmonious partnership at the heart of home life",
    spiritual: "The divine is present in genuine human connection and shared love",
    reversed: "Avoid making major decisions while emotions are running too high or too raw",
  },
  {
    id: 66, name: "Three of Cups", suit: "cups", romanNumeral: "3", symbol: "🥂",
    upright: "Celebration, friendship, family, parties, flirting, and the joy of connection",
    love: "Joyful, social romantic energy; friendship and love intertwine beautifully",
    career: "A positive team environment; celebrate a shared professional achievement",
    money: "Financial celebration or a pleasant social investment is well placed",
    home: "Family gatherings, parties, and the joy of being surrounded by the people you love",
    spiritual: "Community, celebration, and shared joy are deeply nourishing spiritual acts",
    reversed: "Disagreement, guilt from overindulgence, or social or emotional imbalance",
  },
  {
    id: 67, name: "Four of Cups", suit: "cups", romanNumeral: "4", symbol: "😔",
    upright: "Boredom, disillusionment, emotional dissatisfaction, and a withdrawal from what is offered",
    love: "Emotional boredom or dissatisfaction in a relationship; something is missing",
    career: "A professional situation that no longer inspires or fulfils you",
    money: "Disinterest in financial opportunities that are being presented; reassess your values",
    home: "A quiet withdrawal at home; energy is turned inward rather than outward",
    spiritual: "Something is being offered to you that you have not yet noticed; look around you",
    reversed: "Boredom turning into frustration; it is time to make a decision and move",
  },
  {
    id: 68, name: "Five of Cups", suit: "cups", romanNumeral: "5", symbol: "😢",
    upright: "Loss, sadness, disappointment, and grief for what cannot be recovered",
    love: "Grief over a relationship loss or disappointment; salvage what remains and be gentle with yourself",
    career: "A professional disappointment; focus on what can still be salvaged or built anew",
    money: "Financial loss brings grief; acknowledge it honestly and then look toward what remains",
    home: "An emotional loss affecting the home; connection and compassion are needed",
    spiritual: "Grief is part of the soul's journey; do not rush yourself through it",
    reversed: "The bleakest period is ending; confidence and emotional strength are slowly returning",
  },
  {
    id: 69, name: "Six of Cups", suit: "cups", romanNumeral: "6", symbol: "🌹",
    upright: "Nostalgia, old friends, happy memories, and past connections returning",
    love: "A past love or significant connection re-enters; nostalgia carries both sweetness and warning",
    career: "A former colleague, employer, or project returns with renewed potential",
    money: "An old financial arrangement or past investment comes back into view",
    home: "Happy memories, family reconnections, and the comfort of familiar people and places",
    spiritual: "The past holds gifts that are still relevant to your present growth",
    reversed: "An unwelcome visitor or reminder from the past intrudes on your present",
  },
  {
    id: 70, name: "Seven of Cups", suit: "cups", romanNumeral: "7", symbol: "🌈",
    upright: "Excitement, confusion, many possibilities, and the need to wait before choosing",
    love: "Many romantic possibilities create confusion; avoid committing before clarity arrives",
    career: "Multiple exciting professional options are overwhelming; wait for more information",
    money: "Too many financial possibilities create confusion; do not act until the picture clears",
    home: "Exciting but uncertain domestic changes; take time before making a significant move",
    spiritual: "The imagination is rich and active; be discerning about what is vision and what is fantasy",
    reversed: "A dream failing reality; it is time to see the situation clearly and honestly",
  },
  {
    id: 71, name: "Eight of Cups", suit: "cups", romanNumeral: "8", symbol: "🚶",
    upright: "Timely departure, quiet leaving, emotional closure, and moving toward what matters",
    love: "A quiet but necessary departure from something in love that no longer nourishes",
    career: "Leaving a professional situation that has served its purpose; the timing is right",
    money: "Releasing a financial arrangement or investment that is no longer aligned with your path",
    home: "A peaceful but meaningful transition away from something in domestic life",
    spiritual: "The bravest thing you can do is quietly walk away from what no longer feeds your soul",
    reversed: "Abandoning something or someone that still held real potential",
  },
  {
    id: 72, name: "Nine of Cups", suit: "cups", romanNumeral: "9", symbol: "✨",
    upright: "A wish card, dreams coming true, success, and happiness where energy is focused",
    love: "Your deepest romantic wish is within reach; open your heart to receiving it",
    career: "Success and satisfaction in the professional area you have been most focused on",
    money: "Financial wishes and goals have a real chance of materialising now",
    home: "Deep contentment and happiness fill the home; what you wished for is arriving",
    spiritual: "You are in alignment with your deepest desires; the universe responds with a yes",
    reversed: "Self-centredness, ego, or a lack of generosity that blocks the flow of joy",
  },
  {
    id: 73, name: "Ten of Cups", suit: "cups", romanNumeral: "10", symbol: "🕊️",
    upright: "Happiness, peace, beloved people, family growth, and the expansion of home",
    love: "Deep, lasting happiness in love; a relationship that becomes truly like home",
    career: "Work that genuinely fulfils you and aligns with your emotional values",
    money: "Emotional and material abundance flow together in a deeply satisfying way",
    home: "A joyful, peaceful, and expanding family home full of love and shared happiness",
    spiritual: "The highest fulfilment comes through love, belonging, and the sacred ordinary",
    reversed: "Communication issues or unexpressed needs that prevent real progress in a relationship",
  },
  {
    id: 74, name: "Page of Cups", suit: "cups", romanNumeral: "Page", symbol: "🐟",
    upright: "Children, young people, new emotional projects, socialising, and a kind fun-loving person",
    love: "A sweet, sincere, and somewhat innocent romantic energy; something tender is beginning",
    career: "A new creative or emotional project brings genuine excitement and possibility",
    money: "A small but heartfelt financial gift, opportunity, or kind act of generosity",
    home: "Children or young people bring joyful, playful energy into the home",
    spiritual: "Emotional openness and childlike wonder are gateways to your most authentic self",
    reversed: "Emotional immaturity or a superficial social circle makes genuine connection difficult",
  },
  {
    id: 75, name: "Knight of Cups", suit: "cups", romanNumeral: "Knight", symbol: "🦢",
    upright: "A proposal, romantic offer, or emotional invitation; check whether it is genuine",
    love: "A romantic gesture or proposal arrives; beautiful but requiring honest scrutiny",
    career: "A creative or emotionally compelling professional offer is being made",
    money: "A financial offer with emotional appeal; ensure it has real substance behind it",
    home: "A kind and romantic gesture within the home or family context",
    spiritual: "Follow the beauty that calls to you, but do not lose your footing in the real world",
    reversed: "Romantic fantasy without substance, a misleading person, or self-absorbed charm",
  },
  {
    id: 76, name: "Queen of Cups", suit: "cups", romanNumeral: "Queen", symbol: "🧿",
    upright: "Giving and receiving love, creative expression, and deep emotional sensitivity",
    love: "A deeply loving, nurturing, and emotionally attuned partner energy",
    career: "Emotional intelligence and creative sensitivity are powerful professional assets",
    money: "Caring for your emotional wellbeing creates the inner stability that supports financial clarity",
    home: "A home filled with emotional warmth, creativity, and genuine care for everyone in it",
    spiritual: "Your empathy and emotional depth are sacred gifts; honour and protect them",
    reversed: "Mother-figure issues, lack of emotional support, or hurtful words from someone close",
  },
  {
    id: 77, name: "King of Cups", suit: "cups", romanNumeral: "King", symbol: "🌊",
    upright: "Emotional understanding, creativity, family support, and a deeply caring protector",
    love: "A mature, emotionally wise partner who offers safety, support, and genuine understanding",
    career: "Emotional intelligence and creativity lead to respected professional leadership",
    money: "Wise and compassionate financial decisions that take care of those who depend on you",
    home: "A deeply caring and emotionally supportive presence at the heart of the home",
    spiritual: "Emotional mastery and the capacity to hold space for others are among the highest gifts",
    reversed: "Suppressed emotions, control issues, or a domineering person hiding behind charm",
  },
];

export function drawThreeCards(): [TarotCard, TarotCard, TarotCard] {
  const shuffled = [...TAROT_DECK].sort(() => Math.random() - 0.5);
  return [shuffled[0], shuffled[1], shuffled[2]];
}
